apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: knative-samples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: project
            - name: POSTGRES_USER
              value: melo
            - name: POSTGRES_PASSWORD
              value: qaz129946858
