# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: ALPHA
  name: opentelemetry-cloud-run-sample
spec:
  template:
    spec:
      containers:
      - image: philipz/otel-logback:agent
        name: app
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_INSTRUMENTATION_RUNTIME_METRICS_ENABLED
          value: "true"
        - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED
          value: "true"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/otel-auto-instrumentation-java/javaagent.jar"
        - name: OTEL_SERVICE_NAME
          value: "rest-api"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://localhost:4317"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage,b3"
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_traceidratio"
        - name: OTEL_TRACES_SAMPLER_ARG
          value: "0.25"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
      - image: otel/opentelemetry-collector-contrib:0.90.0
        name: collector
        volumeMounts:
          - name: otel-config
            readOnly: true
            mountPath: /etc/otelcol-contrib/
      volumes:
        - name: otel-config
          configMap:
            name: collector-config
